name: Setup Cpolar on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # This runs every 3 hours

jobs:
  setup-cpolar:
    runs-on: windows-latest
    steps:
      - name: Init
        run: |
          Resize-Partition -DriveLetter D -Size ((Get-PartitionSupportedSize -DriveLetter D).SizeMax - 102400MB)
          New-Partition -DiskNumber 1 -UseMaximumSize -AssignDriveLetter  
          Format-Volume -DriveLetter E -FileSystem NTFS -NewFileSystemLabel "NewPartition"
          git clone https://github.com/OIerOrg/CloudPC.git
          pwd
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
          Write-Host "Configuring firewall to allow Remote Desktop..."
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "Setting password for the Administrator account..."
          $username = "runneradmin"
          $plainPassword = "${{ secrets.PASS }}"
          $userAccount = [ADSI]("WinNT://./" + $username + ",user")
          $userAccount.SetPassword($plainPassword)
          Invoke-WebRequest -Uri https://www.cpolar.com/static/downloads/cpolar-stable-windows-amd64.zip -OutFile cpolar.zip
          Expand-Archive -Path cpolar.zip -DestinationPath E:\cpolar
          cd E:\cpolar
          cp C:\Users\runneradmin\CloudPC E:\workspace -r
          .\cpolar authtoken ${{ secrets.CPOLAR_AUTHTOKEN }}
      - name: Move code to E drive
        run: |
          echo "Moving code to E: drive"
          Move-Item -Path "${{ github.workspace }}\*" -Destination "E:\repo" -Force
          Set-Location -Path "E:\repo"
      - name: Start Cpolar
        run: |
          Start-Process -NoNewWindow -FilePath "E:\cpolar\cpolar.exe" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 3600
          Start-Sleep -Seconds 3600
          Start-Sleep -Seconds 3600
          Start-Sleep -Seconds 3600
          Start-Sleep -Seconds 3600
          Start-Sleep -Seconds 3400
        shell: powershell

      # Example Step: Commit Changes (if applicable)
      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit by GitHub Actions" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
