name: Setup Cpolar on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-cpolar:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cpolar
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
          Write-Host "Configuring firewall to allow Remote Desktop..."
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "Setting password for the Administrator account..."
          $username = "Codespace"
          $password = "123456" | ConvertTo-SecureString -AsPlainText -Force
          $userAccount = [ADSI]("WinNT://./" + $username + ",user")
          $userAccount.SetPassword($password)
          Invoke-WebRequest -Uri https://www.cpolar.com/static/downloads/cpolar-stable-windows-amd64.zip -OutFile cpolar.zip
          Expand-Archive -Path cpolar.zip -DestinationPath C:\cpolar
          cd C:\cpolar
          .\cpolar authtoken ${{ secrets.CPOLAR_AUTHTOKEN }}

      - name: Start Cpolar
        run: |
          Start-Process -NoNewWindow -FilePath "C:\cpolar\cpolar.exe" -ArgumentList "tcp 3389"
          sleep 1000
        shell: powershell
